import Head from 'next/head'
import { Inter } from '@next/font/google';
import HeroSection from '../components/sections/HeroSection';
import LearnSection from '../components/sections/LearnSection';
import ProviderSection from '../components/sections/ProviderSection';
import BehindSection from '../components/sections/BehindSection';
import GallerySection from '../components/sections/GallerySection';
import Footer from '../components/ui/Footer';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='h-screen w-screen relative'>
        <HeroSection/>
        <LearnSection/>
        <ProviderSection/>
        <BehindSection/>
        <GallerySection/>
        <Footer/>
      </div>
    </>
  )
}
